name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: write  # IMPORTANTE: Permiso para publicar el reporte

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Resolve Dependencies
        run: mvn dependency:resolve

      # Ejecutamos los tests, pero agregamos "continue-on-error"
      # Si un test falla, queremos que el pipeline siga para generar el reporte
      - name: Run Tests with Maven
        run: mvn clean test
        continue-on-error: true

      # Generamos la carpeta con el HTML del reporte
      - name: Generate Allure Report
        run: mvn allure:report

      # Publicamos esa carpeta en GitHub Pages
      - name: Deploy Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always() # Se ejecuta siempre, pase lo que pase
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./target/site/allure-maven-plugin